/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpkg;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import stegenography.Stegenography;

/**
 *
 * @author neha
 */
public class Stego extends javax.swing.JFrame {
    private Component File;
    

    /**
     * Creates new form Stego
     */
    public Stego() {
        initComponents();
        lblMsg.setText("Please choose image file and text file (*.txt)");
        lblInfo.setText("Use : c:/ <filename>.<jpg>");
        txtImageloc.setText("");
        txtTargetLoc.setText("");
        txtWaterMark.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageFileChoose = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlMark = new javax.swing.JPanel();
        txtImageloc = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        txtWaterMark = new javax.swing.JTextField();
        btnMarkIt = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        txtTargetLoc = new javax.swing.JTextField();
        lblInfo2 = new javax.swing.JLabel();
        lblCustTxt = new javax.swing.JLabel();
        lblSelectImage = new javax.swing.JLabel();
        pnlHide = new javax.swing.JPanel();
        lblSelectImage2 = new javax.swing.JLabel();
        txtImageLoc2 = new javax.swing.JTextField();
        btnBrowse2 = new javax.swing.JButton();
        lblSelectFile = new javax.swing.JLabel();
        txtSelectFile = new javax.swing.JTextField();
        btnFile = new javax.swing.JButton();
        btnHide = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnlRetreive = new javax.swing.JPanel();
        lblSelectImage3 = new javax.swing.JLabel();
        txtImageloc4 = new javax.swing.JTextField();
        btnBrowse3 = new javax.swing.JButton();
        lblRetrieve = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaData = new javax.swing.JTextArea();
        btnRetrieve = new javax.swing.JButton();
        lblinfo3 = new javax.swing.JLabel();
        btnSaveas = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stegnography / Water mark");

        txtImageloc.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        btnBrowse.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnBrowse.setText("Browse...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        txtWaterMark.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        txtWaterMark.setToolTipText("");

        btnMarkIt.setText("Mark It !");
        btnMarkIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkItActionPerformed(evt);
            }
        });

        lblInfo.setText("Use : c:/ <filename>.<jpg>");

        txtTargetLoc.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        lblInfo2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblInfo2.setText("Gave Image name with full path");

        lblCustTxt.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblCustTxt.setText("Custome Text");

        lblSelectImage.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblSelectImage.setText("Select Image");

        javax.swing.GroupLayout pnlMarkLayout = new javax.swing.GroupLayout(pnlMark);
        pnlMark.setLayout(pnlMarkLayout);
        pnlMarkLayout.setHorizontalGroup(
            pnlMarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtWaterMark)
                    .addGroup(pnlMarkLayout.createSequentialGroup()
                        .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 441, Short.MAX_VALUE)
                        .addComponent(btnMarkIt))
                    .addComponent(txtTargetLoc)
                    .addGroup(pnlMarkLayout.createSequentialGroup()
                        .addComponent(txtImageloc)
                        .addGap(18, 18, 18)
                        .addComponent(btnBrowse))
                    .addGroup(pnlMarkLayout.createSequentialGroup()
                        .addGroup(pnlMarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfo2)
                            .addComponent(lblCustTxt)
                            .addComponent(lblSelectImage))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMarkLayout.setVerticalGroup(
            pnlMarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarkLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSelectImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtImageloc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCustTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWaterMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTargetLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMarkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarkIt)
                    .addComponent(lblInfo))
                .addGap(54, 54, 54))
        );

        jTabbedPane1.addTab("Water mark", pnlMark);

        lblSelectImage2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblSelectImage2.setText("Select Image");

        txtImageLoc2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        btnBrowse2.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnBrowse2.setText("Browse..");
        btnBrowse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowse2ActionPerformed(evt);
            }
        });

        lblSelectFile.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblSelectFile.setText("Select Any File");

        txtSelectFile.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        btnFile.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnFile.setText("Choose File...");
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        btnHide.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnHide.setText("Hide...");
        btnHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideActionPerformed(evt);
            }
        });

        lblMsg.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblMsg.setText("Please Select Image file and Text file (*.txt)");

        jButton1.setText("Slect Audo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hde");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHideLayout = new javax.swing.GroupLayout(pnlHide);
        pnlHide.setLayout(pnlHideLayout);
        pnlHideLayout.setHorizontalGroup(
            pnlHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelectFile)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHideLayout.createSequentialGroup()
                        .addComponent(lblSelectImage2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtImageLoc2, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBrowse2))
                    .addGroup(pnlHideLayout.createSequentialGroup()
                        .addComponent(txtSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFile)))
                .addContainerGap())
            .addGroup(pnlHideLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlHideLayout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(btnHide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(101, 101, 101))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHideLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(90, 90, 90))
        );
        pnlHideLayout.setVerticalGroup(
            pnlHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectImage2)
                    .addComponent(txtImageLoc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse2))
                .addGap(18, 18, 18)
                .addComponent(lblSelectFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSelectFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFile))
                .addGap(48, 48, 48)
                .addGroup(pnlHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHide)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hide Data", pnlHide);

        lblSelectImage3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblSelectImage3.setText("Select Image");

        txtImageloc4.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        btnBrowse3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnBrowse3.setText("Browse...");
        btnBrowse3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowse3ActionPerformed(evt);
            }
        });

        lblRetrieve.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        lblRetrieve.setText("Retreive Text");

        jtaData.setColumns(20);
        jtaData.setRows(5);
        jScrollPane1.setViewportView(jtaData);

        btnRetrieve.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnRetrieve.setText("Retreive");
        btnRetrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveActionPerformed(evt);
            }
        });

        lblinfo3.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        btnSaveas.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        btnSaveas.setText("Save ");
        btnSaveas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveasActionPerformed(evt);
            }
        });

        jButton3.setText("Retrve Audo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRetreiveLayout = new javax.swing.GroupLayout(pnlRetreive);
        pnlRetreive.setLayout(pnlRetreiveLayout);
        pnlRetreiveLayout.setHorizontalGroup(
            pnlRetreiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRetreiveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRetreiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlRetreiveLayout.createSequentialGroup()
                        .addComponent(lblRetrieve)
                        .addGap(101, 101, 101)
                        .addComponent(lblinfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRetrieve)
                        .addContainerGap())
                    .addGroup(pnlRetreiveLayout.createSequentialGroup()
                        .addGroup(pnlRetreiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRetreiveLayout.createSequentialGroup()
                                .addComponent(lblSelectImage3)
                                .addGap(18, 18, 18)
                                .addComponent(txtImageloc4, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(pnlRetreiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRetreiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnBrowse3)
                                .addGroup(pnlRetreiveLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(btnSaveas)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRetreiveLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(49, 49, 49))))))
        );
        pnlRetreiveLayout.setVerticalGroup(
            pnlRetreiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRetreiveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRetreiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectImage3)
                    .addComponent(txtImageloc4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse3))
                .addGroup(pnlRetreiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRetreiveLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlRetreiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRetrieve)
                            .addComponent(lblinfo3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlRetreiveLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetrieve)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRetreiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRetreiveLayout.createSequentialGroup()
                        .addComponent(btnSaveas)
                        .addGap(43, 43, 43)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Retrieve", pnlRetreive);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        lblInfo.setText("Use : c:/ <filename>.<jpg>");
        int retVal = ImageFileChoose.showOpenDialog(File);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg", "PNG file", "png");
         if (retVal== JFileChooser.APPROVE_OPTION) {
            ImageFileChoose.setFileFilter(filter);
            txtImageloc.setText(ImageFileChoose.getSelectedFile().getAbsolutePath());
         }
         txtTargetLoc.setText(txtImageloc.getText());
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnMarkItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkItActionPerformed
        System.out.println(txtImageloc.getText());
        
              
        try {
                File file = new File(txtImageloc.getText());
                if (!file.exists()) {
                        JOptionPane.showMessageDialog(this, "Please select Image", "Warning", JOptionPane.ERROR_MESSAGE);
                }
                    
            ImageIcon icon = new ImageIcon(file.getPath());
            BufferedImage bufferedImage = new BufferedImage(icon.getIconWidth(), icon.getIconHeight(), BufferedImage.TYPE_INT_RGB);
            Graphics2D g2d = (Graphics2D) bufferedImage.getGraphics();
            g2d.drawImage(icon.getImage(), 0, 0, null);
            AlphaComposite alpha = AlphaComposite.getInstance(
            AlphaComposite.SRC_OVER, 0.5f);
            g2d.setComposite(alpha);
            g2d.setColor(Color.white);
            g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
            RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
            g2d.setFont(new Font("Arial", Font.BOLD, 30));
            String watermark = txtWaterMark.getText();
            FontMetrics fontMetrics = g2d.getFontMetrics();
            Rectangle2D rect = fontMetrics.getStringBounds(watermark, g2d);
            g2d.drawString(watermark, (icon.getIconWidth() - (int) rect
            .getWidth()) / 2, (icon.getIconHeight() - (int) rect
            .getHeight()) / 2);
            g2d.dispose();
            File fileout = new File(txtTargetLoc.getText());
            ImageIO.write(bufferedImage, "jpg", fileout);
            lblInfo.setText("Water Marking Successful");
        } catch (IOException ioe) {
            }
    }//GEN-LAST:event_btnMarkItActionPerformed

    private void btnBrowse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowse2ActionPerformed
         lblMsg.setText("Please choose image file and text file (*.txt)");
        int retVal = ImageFileChoose.showOpenDialog(File);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg", "PNG file", "png");
         if (retVal== JFileChooser.APPROVE_OPTION) {
            ImageFileChoose.setFileFilter(filter);
            txtImageLoc2.setText(ImageFileChoose.getSelectedFile().getAbsolutePath());
         }
         
    }//GEN-LAST:event_btnBrowse2ActionPerformed

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
         lblMsg.setText("Please choose image file and text file (*.txt)");
        int retVal = ImageFileChoose.showOpenDialog(File);
        if (retVal== JFileChooser.APPROVE_OPTION) {        
            txtSelectFile.setText(ImageFileChoose.getSelectedFile().getAbsolutePath());
         }
         
    }//GEN-LAST:event_btnFileActionPerformed

    private void btnHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideActionPerformed
        String Imageurl = txtImageLoc2.getText();
        String Fileurl = txtSelectFile.getText();
        
        Stegenography steg = new Stegenography();
        steg.hide(Fileurl, Imageurl);
        lblMsg.setText("File Processed Successful");
    }//GEN-LAST:event_btnHideActionPerformed

    private void btnBrowse3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowse3ActionPerformed
       lblinfo3.setText("");
        int retVal = ImageFileChoose.showOpenDialog(File);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPEG file", "jpg", "jpeg", "PNG file", "png");
         if (retVal== JFileChooser.APPROVE_OPTION) {
            ImageFileChoose.setFileFilter(filter);
            txtImageloc4.setText(ImageFileChoose.getSelectedFile().getAbsolutePath());
         }
    }//GEN-LAST:event_btnBrowse3ActionPerformed

    private void btnRetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveActionPerformed
        String ImageUrl = txtImageloc4.getText();
        Stegenography steg = new Stegenography();
        String getMsg = steg.reveal(ImageUrl);
        jtaData.setText(getMsg);
        lblinfo3.setText("File Processed Successful");
    }//GEN-LAST:event_btnRetrieveActionPerformed

    private void btnSaveasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveasActionPerformed
        Stegenography steg = new Stegenography();
        String endMsg = steg.save();
        lblinfo3.setText("File saved with a name " + endMsg);
    }//GEN-LAST:event_btnSaveasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int retVal = ImageFileChoose.showOpenDialog(File);
        if (retVal== JFileChooser.APPROVE_OPTION) {        
            txtSelectFile.setText(ImageFileChoose.getSelectedFile().getAbsolutePath());
         }

        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
    int val;
     FileInputStream fis=new FileInputStream(txtSelectFile.getText());
FileOutputStream fos=new FileOutputStream("d:/a.mp3");
    while(( val=fis.read())!=-1){
            fos.write(val);
    }
fos.close();
fis.close();

}catch(Exception o){
    System.err.println(""+o);
} 

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

try{

   if(txtImageloc4.getText().length()==0){
   JOptionPane.showMessageDialog(null, "select image file");
   }
   else
    Runtime.getRuntime().exec("cmd /c  d:/a.mp3");
}catch(Exception e){

    System.err.println(""+e);
}        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Stego().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser ImageFileChoose;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnBrowse2;
    private javax.swing.JButton btnBrowse3;
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnHide;
    private javax.swing.JButton btnMarkIt;
    private javax.swing.JButton btnRetrieve;
    private javax.swing.JButton btnSaveas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jtaData;
    private javax.swing.JLabel lblCustTxt;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblInfo2;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblRetrieve;
    private javax.swing.JLabel lblSelectFile;
    private javax.swing.JLabel lblSelectImage;
    private javax.swing.JLabel lblSelectImage2;
    private javax.swing.JLabel lblSelectImage3;
    private javax.swing.JLabel lblinfo3;
    private javax.swing.JPanel pnlHide;
    private javax.swing.JPanel pnlMark;
    private javax.swing.JPanel pnlRetreive;
    private javax.swing.JTextField txtImageLoc2;
    private javax.swing.JTextField txtImageloc;
    private javax.swing.JTextField txtImageloc4;
    private javax.swing.JTextField txtSelectFile;
    private javax.swing.JTextField txtTargetLoc;
    private javax.swing.JTextField txtWaterMark;
    // End of variables declaration//GEN-END:variables
}
